sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_0e10571da8c0_key -iv $encrypted_0e10571da8c0_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- export CONSUMER_KEY=3MVG9TSaZ8P6zP1pZrmMghgZXjdvsZeP7wHqnVUCYzG6W.l9RUnzSMX3gK0H6.xXSJsy1rnuhhFK2zevUw92d
- export JWT_KEY_FILE=assets/server.key
- export USERNAME=paul.birkinhead@express-gifts.co.uk
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- ./sfdx/install
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile $JWT_KEY_FILE --username $USERNAME --setdefaultdevhubusername -a HubOrg
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait
  2
- sfdx force:org:display -u ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg --wait 10
- sfdx force:org:delete -u ciorg -p
